- .github/workflows/release.yaml
This PR makes it so we don't rely on `bash` and `yq` magic to build the list of images to build, but instead can use proper typescript. It also prints the list of changed images to the step stummary.
Additionally the change adds a quick `if` check to the build step. It seems obsolete for now because the entire workflow only runs when files in `apps/**` change, but if this were to ever change this is a nice and simple way to prevent accidental builds.
> ci: Use script to determine apps to build, don't build if no apps changed

- .github/workflows/image-build-action.yaml
We can keep these in the same job to cut down on LoC and needs in the notify plus cosign or sbom doesn't take long enough to really benefit from sign and attest running in parallel
> ci: merge sign and attest

- .renovaterc.json5
- apps/plex/Dockerfile
This also switches Plex back to 24.04 which is the LTS, I can't see a reason to use releases after that?
> ci: pin base images for certain containers

- apps/actions-runner/Dockerfile
@buroa was there a reason this was removed? It could still come in handy in places. There's no way to get brew installed without these changes.
> fix(actions-runner): add brew back for amd64

- .github/workflows/image-build-action.yaml
- Removed code scanning, opened #236 to be completed in another PR.
- Added [annotations to the file index](https://docs.docker.com/build/metadata/annotations/) because [GitHub package overview](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#adding-a-description-to-multi-arch-images) will show more information
- Switched to [actions/attest-build-provenance](https://github.com/actions/attest-build-provenance?tab=readme-ov-file), this should also remove the need for cosign (see [here](https://github.com/actions/attest-build-provenance/issues/62#issuecomment-2096500208))
- Added Verify Attestation step
> ci: improve attestation

- .github/workflows/release.yaml
This moves the release workflow away from `tj-actions/changed-files` in favor of my own action.
Additionally it reworks the input parsing for the `Extract Metadata` step to make it less prone to script injections.
> ci: Move away from tj-actions/changed-files

- apps/theme-park/Dockerfile
The old version dumped everything right into `/usr/share/nginx/html/` instead of sorting stuff into folders like `css/` and `resources/`. This tweak fixes the Dockerfile so files end up where they’re supposed to be, making sure everything works as expected.
Tested on my containers repo and this fixed the directory path issues I was having. 
Also neovim auto formatted on write.. so just a couple indentation changes.
> fix(theme-park): Fix Directory Structure

- .github/workflows/image-build-action.yaml
- .github/workflows/retry-release.yaml
- .github/workflows/vulnerability-scan.yaml
Such a stupid hack but it's needed
- https://github.com/orgs/community/discussions/25768
- https://github.com/orgs/community/discussions/10553
- https://github.com/orgs/community/discussions/27086
- ...
I went with using github-script, but we could use bash instead e.g.
```yaml
- # Ref: https://github.com/orgs/community/discussions/25768
name: Lowercase Vars Hack
id: vars
run: echo "repository_owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
```
Fixes: #260
> ci: add lower-case repo owner hack

- apps/k8s-sidecar/.dockerignore
- apps/k8s-sidecar/Dockerfile
- apps/k8s-sidecar/docker-bake.hcl
- apps/k8s-sidecar/tests.yaml
The developer of this application is pretty derp and won't support adding in a few useful CLI tools because:
> Adding more binaries to the image does not really match the philosophy of the project having a minimal image and hence minimal attack surface.
See here https://www.github.com/kiwigrid/k8s-sidecar/issues/271
> feat(k8s-sidecar): add new image

- apps/webhook/Dockerfile
I would like to find a replacement but jq works for now.
> fix(webhook): remove jsonpath bash script for now

- apps/irqbalance/Dockerfile
- apps/postgres-init/Dockerfile
- apps/qbittorrent/Dockerfile
- apps/sabnzbd/Dockerfile
- apps/transmission/Dockerfile
- remove jo & trurl pkgs from qb & sab
- use double equal operator for installing alpine pkgs
> fix: remove jo & trurl pkgs from qb & sab [ci-skip]

- apps/home-assistant/Dockerfile
Noticed that with the Home Assistant Voice Preview that without the mim.types the response playback fails.  See this issue: https://github.com/esphome/home-assistant-voice-pe/issues/378#issuecomment-2783815609
> fix(home-assistant): Add mailcap to install /etc/mime.types for proper tts proxy support

- apps/deluge/Dockerfile
- apps/deluge/entrypoint.sh
Adds too much jank to the entrypoint since the args do not get auto updated in the config files
> feat(deluge): revert allow port customizations

- apps/qbittorrent/Dockerfile
- apps/qbittorrent/defaults/qBittorrent.conf
Due to the nature of changing config options in the UI, it is not best to have these env defaulted in the container.
This is not a breaking change as anyone who deployed QB without any env set their config file holds the ports being used.
Fixes #362
> fix(qb): do not set ports as env

- .renovaterc.json5
- apps/beets/Dockerfile
Found a way around the build errors when using Node v22 (LTS)
> fix(beets): use latest nodejs

- apps/deluge/Dockerfile
- apps/deluge/docker-bake.hcl
Repology datasource looks broken, no updates were discovered.
> feat(deluge): update to v2.2.0

- apps/deluge/Dockerfile
- apps/qbittorrent/Dockerfile
- apps/transmission/Dockerfile
Alpine no longer provides p7zip, it just links to 7zip so might as well use the actual package name that is installed.
> fix: switch from p7zip to 7zip

- .renovaterc.json5
- apps/bazarr/Dockerfile
- apps/beets/Dockerfile
- apps/esphome/Dockerfile
- apps/jbops/Dockerfile
- apps/nzbget/Dockerfile
- apps/qbittorrent/Dockerfile
- apps/sabnzbd/Dockerfile
- apps/tautulli/Dockerfile
- apps/theme-park/Dockerfile
- apps/webhook/Dockerfile
When a new major version of python or alpine are released, we need to be careful as these updates might break builds. This PR essentially makes updating python or alpine versions a manual task across all apps.
We need to be careful when new major versions are released for those base images.
> fix: pin alpine and python versions across all apps [ci-skip]

- apps/postgres-init/entrypoint.sh
This pull request adds a new configuration option to the apps/postgres-init/entrypoint.sh script, enabling the creation of databases with UTF8 encoding when specified. These changes improve flexibility during database initialization.
If the environment variable INIT_POSTGRES_UTF8 is not set, the initial database script retains its previous behavior.
The INIT_POSTGRES_UTF8 variable only accepts the value "true" to enable UTF8 encoding.
> ✨🐘 feat(postgres-init): Add support for UTF-8 database creation

- apps/sabnzbd/entrypoint.sh
Maps entries in `SABNZBD__LOCAL_RANGES_ENTRIES` to the `local_ranges` config option in `sabnzbd.ini`.
Fixes access from  RFC 6598 ip ranges used in some Kubernetes deployments.
[RFC 6598 IP ranges](https://en.wikipedia.org/wiki/Carrier-grade_NAT#Shared_address_space) are sometimes used in Kubernetes deployments to allocate IP space to the pod network that does not overlap with existing on-prem network addressing. In my case, I have used the 100.64.0.0/16 range for my pod network.
SABnzbd  maintains some internal list of "private" networks, and by default it refuses requests from CIDRs outside of that list. This behavior can be overriden by configuring the `local_ranges` option, but for users deploying the app to Kubernetes, this means jumping through additional hoops.
Adding this option …
> feat(sabnzbd): adds ENV VAR to configure local_ranges in config.ini

- .github/actions/app-tests/run.sh
- .github/actions/container-size-diff/action.yaml
- .github/actions/container-size-diff/container-size-diff.sh
- .github/workflows/app-builder.yaml
- .github/workflows/pull-request.yaml
Support posting a container diff of the new image and previous image. Kindly "inspired" by https://github.com/philips-software/amp-devcontainer/tree/09d0fb4c4601281473bed279fca0d66bf52a26e0/.github/actions/container-size-diff
Some changes needed to be made for this to happen...
1. Push tags for PR builds under a mutable `:sandbox` tag
2. Move testing container to it's own job stage which references the `:sandbox` tag
Benefits:
1. See size diffs of the container in the PR.
2. Test built images in $prod before they are merged.
Drawbacks:
1. Some glue, some maintenance.
> ci: post the container size diff to the pull request

- apps/pyload-ng/Dockerfile
- apps/pyload-ng/defaults/pyload.cfg
- apps/pyload-ng/docker-bake.hcl
- apps/pyload-ng/entrypoint.sh
- apps/pyload-ng/tests.yaml
this adds pyload-ng container.
pyload-ng itself is a pre-release; hope that is not a problem.
~had to use python:3.13-slim because current versions of alpine do not ship `unrar` / `unrar-free` (https://gitlab.alpinelinux.org/alpine/aports/-/issues/17506) and i dont think building it from source is feasible.~
EDIT: image now uses alpine and unrar build by LS.
`entrypoint.sh` copies a default config, when missing, with updated `ip host : "IP address" = 0.0.0.0`.
pyload listens only on localhost per default and i did not find another way.
(not build for ENV support...)
hope this ships with most dependencies to support a variety of plugins.
tested download of rar, zip, tar.gz with auto unpack and it worked.
im not sure how and if multiarch builds work.
is the usage of `VOLUME` in `Dockerfile` …
> add pyload-ng container
