- .github/workflows/image-build-action.yaml
- .github/workflows/release.yaml
> feat: add sboms

- apps/theme-park/Dockerfile
- apps/theme-park/metadata.yaml
- apps/theme-park/tests.yaml
no rootless container exists upstream
> feat: add theme-park

- .github/workflows/image-build-action.yaml
Vars will be stored as `version_${app_name}` with dashes replaced with underscores
> feat: store version info in github repo vars

- .github/workflows/image-build-action.yaml
Reverts home-operations/containers#205
> Revert "feat: store version info in github repo vars"

- apps/transmission/Dockerfile
- apps/transmission/metadata.yaml
- apps/transmission/tests.yaml
Aligns with nzbget, sabnzbd and qbittorrent
> feat(transmission): use python alpine base

- apps/qbittorrent/Dockerfile
- apps/qbittorrent/tests.yaml
Aligns image with transmission, sabnzbd and nzbget
> feat(qb): use python alpine base and add unrar

- apps/qbittorrent/Dockerfile
> fix(qb): remove qt pkgs

- .github/workflows/image-build-action.yaml
- apps/plex/Dockerfile
- apps/sonarr/metadata.yaml
- This isn't needed
- Also use gh cli to grab testing tools
> chore(plex): remove force conf old arg

- apps/theme-park/Dockerfile
> fix(theme-park): use 1.27-alpine base

- apps/actions-runner/Dockerfile
this is included in the github hosted runners, I see no reason to not include it here
> feat(actions-runner): add gh cli

- .github/actions/definitive-versions/action.yml
- .github/actions/test-container/action.yml
- .github/actions/test-container/run.sh
- .github/actions/test-container/setup.sh
- .github/workflows/image-build-action.yaml
- .github/workflows/test-version.yaml
- Broke out the testing of containers into a composite action
- Broke out the version logic into a composite action
- Created a workflow where we can call a workflow dispatch to test an input version to get the outputs.
- Fixes #248
> ci: add composite actions

- .github/workflows/image-build-action.yaml
- .github/workflows/retry-release.yaml
- .github/workflows/vulnerability-scan.yaml
Rename the hack to Setup Vars and make more use of it in the image build workflow call
> ci: a better way to do runs-on

- apps/esphome/Dockerfile
I assume its an leftover and not needed ?
> fix(esphome): remove cache workdir

- .github/workflows/image-builder.yaml
- .github/workflows/pull-request.yaml
- .github/workflows/release.yaml
- apps/bazarr/Dockerfile
- apps/esphome/Dockerfile
- apps/home-assistant/Dockerfile
- apps/jackett/Dockerfile
- apps/jbops/Dockerfile
- apps/lidarr/Dockerfile
- apps/nzbget/Dockerfile
- apps/plex/Dockerfile
- apps/postgres-init/Dockerfile
- apps/prowlarr/Dockerfile
- apps/radarr/Dockerfile
- apps/readarr/Dockerfile
- apps/sonarr/Dockerfile
- apps/tautulli/Dockerfile
Also test out the new action version to verify all apps can be changed
> chore: update COPY for all apps [ci-skip]

- apps/emby/Dockerfile
- apps/emby/entrypoint.sh
- apps/emby/tests.yaml
> chore(emby): updates to the build

- apps/webhook/.dockerignore
- apps/webhook/Dockerfile
- apps/webhook/docker-bake.hcl
- apps/webhook/entrypoint.sh
- apps/webhook/tests.yaml
https://github.com/adnanh/webhook
With apprise and https://github.com/bashtools/JSONPath.sh
> feat: add webhook container

- apps/webhook/entrypoint.sh
> fix(webhook): define hooks param

- apps/opentofu-runner/.dockerignore
- apps/opentofu-runner/Dockerfile
- apps/opentofu-runner/docker-bake.hcl
- apps/opentofu-runner/tests.yaml
src: https://github.com/joryirving/containers
> feat(opentofu): add new image

- apps/home-assistant/Dockerfile
https://discord.com/channels/673534664354430999/1088081671686996008/1356731483460603966
> fix(hass): set PYTHONUSERBASE

- apps/it-tools/.dockerignore
- apps/it-tools/Dockerfile
- apps/it-tools/docker-bake.hcl
- apps/it-tools/tests.yaml
Adds https://github.com/CorentinTh/it-tools
> feat: add it-tools container

- .github/workflows/app-builder.yaml
- .github/workflows/retry-release.yaml
- .github/workflows/vulnerability-scan.yaml
- README.md
> ci: no more lowering repo owner or repo name

- apps/atuin-server-sqlite/.dockerignore
- apps/atuin-server-sqlite/Dockerfile
- apps/atuin-server-sqlite/docker-bake.hcl
- apps/atuin-server-sqlite/tests.yaml
- Atuin doesn't support sqlite
- The sqlite "fork" of atuin doesn't support arm64
Upstream support might be added in the future https://github.com/atuinsh/atuin/issues/2502
> feat: add atuin-server-sqlite

- apps/actions-runner/Dockerfile
- apps/atuin-server-sqlite/Dockerfile
- apps/bazarr/Dockerfile
- apps/beets/Dockerfile
- apps/cni-plugins/Dockerfile
- apps/emby/Dockerfile
- apps/esphome/Dockerfile
- apps/home-assistant/Dockerfile
- apps/irqbalance/Dockerfile
- apps/it-tools/Dockerfile
- apps/jackett/Dockerfile
- apps/jbops/Dockerfile
- apps/k8s-sidecar/Dockerfile
- apps/lidarr/Dockerfile
- apps/nzbget/Dockerfile
- apps/opentofu-runner/Dockerfile
- apps/plex/Dockerfile
- apps/postgres-init/Dockerfile
- apps/prowlarr/Dockerfile
- apps/qbittorrent/Dockerfile
- apps/radarr/Dockerfile
- apps/readarr/Dockerfile
- apps/sabnzbd/Dockerfile
- apps/sonarr/Dockerfile
- apps/tautulli/Dockerfile
- apps/theme-park/Dockerfile
- apps/transmission/Dockerfile
- apps/volsync/Dockerfile
- apps/webhook/Dockerfile
- Remove hadolint comments/annotations, we don't enforce these nor have the ambition to. Maybe in the future.
- Remove most case statements for determining ARCH <https://www.docker.com/blog/new-dockerfile-capabilities-v1-7-0/>
- Add [buildkit annotations](https://docs.docker.com/build/buildkit/frontend/) to dockerfiles
- Removed additional cruft from dockerfiles
> chore: dockerfile style updates [ci-skip]

- apps/deluge/Dockerfile
- apps/deluge/entrypoint.sh
and bind all interfaces to `0.0.0.0`
> feat(deluge): allow port customizations

- apps/bazarr/Dockerfile
uv doesn't support same line modifications in requirements.txt https://github.com/astral-sh/uv/issues/4420
> fix(bazarr): use uv to install python deps

- apps/transmission/Dockerfile
- apps/transmission/entrypoint.sh
> feat(transmission): allow disabling env substitution

- .renovaterc.json5
- apps/qbittorrent/Dockerfile
- apps/qbittorrent/docker-bake.hcl
- apps/qbittorrent/entrypoint.sh
Alpine is lagging quite a bit on arm64 builds
> feat(qbittorrent): switch back to userdocs build

- apps/qbittorrent/Dockerfile
Thanks evilnotes for the pointers. Worth giving this a try here and see if there's any noticable performance gains or issues.
> feat(qbittorrent): switch to using mimalloc

- apps/qbittorrent/Dockerfile
- apps/radarr/Dockerfile
- apps/sabnzbd/Dockerfile
After days of running these applications with mimalloc2 there wasn't any noticeable improvements to CPU or memory usage for these three applications.
> revert: mimalloc2 experiment

- apps/sabnzbd/Dockerfile
- apps/sabnzbd/tests.yaml
https://pkgs.alpinelinux.org/packages?name=par2cmdline-turbo&branch=edge&repo=&arch=&origin=&flagged=&maintainer=
> fix(sabnzbd): install par2cmdline-turbo from alpine testing

- apps/nzbget/Dockerfile
- apps/sabnzbd/Dockerfile
See https://github.com/nzbgetcom/nzbget/issues/81
> fix: use 7zip for sabnzbd and nzbget

- .renovaterc.json5
- apps/bazarr/Dockerfile
> fix(bazarr): bump to Python 3.13

- .renovaterc.json5
- apps/cni-plugins/Dockerfile
- apps/deluge/Dockerfile
- apps/irqbalance/Dockerfile
- apps/irqbalance/docker-bake.hcl
- apps/jackett/Dockerfile
- apps/lidarr/Dockerfile
- apps/opentofu-runner/Dockerfile
- apps/postgres-init/Dockerfile
- apps/postgres-init/docker-bake.hcl
- apps/prowlarr/Dockerfile
- apps/radarr/Dockerfile
- apps/readarr/Dockerfile
- apps/smartctl-exporter/Dockerfile
- apps/sonarr/Dockerfile
- apps/whisparr/Dockerfile
Only updates standard alpine images to 3.22.
> feat: upgrade standard alpine base images to 3.22

- apps/esphome/Dockerfile
See https://github.com/home-operations/containers/issues/597
Reverts home-operations/containers#603
> Revert "fix(esphome): use slim debian base image"

- .renovaterc.json5
- apps/nzbhydra2/Dockerfile
Waiting on https://www.github.com/corretto/corretto-docker/issues/238
> fix(nzbhydra2): bump to alpine 3.22

- apps/nzbget/entrypoint.sh
> fix(nzbget): disable log file
